### ISSUE TITLE
Error due to a large number of columns for ensemble forecasts verification

### ISSUE THREAD

**Issue by Ciccuz** [WFRT/verif#103]
Hello, this is my first Issue so if I do some errors in posting or other things please let me know.
I'm trying to use verif for verification of ensemble forecasts: I wrote a txt file as explained in https://github.com/WFRT/verif/wiki/Arranging-my-own-data having the following columns: date, hour, leadtime, obs, fcst, 16 quantiles columns and 525 ensemble realization columns, resulting in a file with 546 columns; I noticed that if the number of columns is too large when initializing the input data with verif.data.Data(verif.input.get_input('filename.txt')) I get this error "Error: Incorrect number of columns (expecting 546) in row '20181027 01 0 ...' ".
I tried reducing the number of columns and apparently it works for files with less than 256 columns.
I searched quite a lot but I haven't found any solution to this problem, is this a bug or am I missing something?

**Comment by tnipen** [comment]
Usually the error means that your header row doesn't have the same number of columns as one of your data rows. Feel free to email me the file (thomasn@met.no) and I can have a look.
