### ISSUE TITLE
text2nc and ens2prob do not take into acount the ensemble members

### ISSUE THREAD

**Issue by DikraK** [WFRT/verif#104]
I have a text file which I organized as requested  with members  from e0 to e23 (see below for an extract).
The script text2nc.py does  take into account all the variable except the members,  ens2prob.py does the same thing. Could you help me that ? 

Thanks in advance!

here is an extract of my text file:
# variable: Precipitation 
# units: $mm$ 
unixtime location lat lon obs fcst   e0  ....  ................................................         e23 
1529150400   77777      52.58     149.67    0.00000    0.00000    0.00000  ...  0.02128  
1529172000    77777     52.58     149.67    0.00000    0.00000    0.00000   ...   0.03775
1529193600    77777     52.58     149.67    0.00000    0.98722    1.37504   ...   0.05344

**Comment by tnipen** [comment]
You can use ens2prob.py to convert the ensemble information in your file to probabilistic information, which can be read by Verif. For example:

`python ens2prob.py file.txt file.nc -r 0.1,0.5,1,2,5`

will create cumulative probability values for a number of thresholds. This can then be used by the reliability diagram for example:

`verif file.nc -m reliability -r 0.1`

**Comment by DikraK** [comment]
> You can use ens2prob.py to convert the ensemble information in your file to probabilistic information, which can be read by Verif. For example:
> 
> `python ens2prob.py file.txt file.nc -r 0.1,0.5,1,2,5`
> 
> will create cumulative probability values for a number of thresholds. This can then be used by the reliability diagram for example:
> 
> `verif file.nc -m reliability -r 0.1`

Thanks that works!

**Comment by tnipen** [comment]
Good to hear! :)
