### ISSUE TITLE
How to arrange my data to Compute probabilistic information from ensemble?

### ISSUE THREAD

**Issue by Marcoii1801** [WFRT/verif#108]
I have ensemble (50 members) forecast data from ECMWF  and i would like to compute the probfile.nc to use it with verif, but when I run the ens2prob.py script I get the next error:

  File "ens2prob.py", line 163, in <module>
    main()
  File "ens2prob.py", line 38, in main
    ens = copy.deepcopy(ifile.ensemble)
AttributeError: 'Text' object has no attribute 'ensemble'

[ENS_27052017.txt](https://github.com/WFRT/verif/files/3673788/ENS_27052017.txt)

I am attaching the txt file that i am using. Variable: Total Precipitation, units: mm

thanks

**Comment by tnipen** [comment]
This required the lastes version of Verif, which was only available by installing from source. I have made a new pip package (v1.1.0), which supports this.

**Comment by Marcoii1801** [comment]
Hello Thomas

I installed the last version from the source, but now i got a
different error:

ens2prob.py:72: RuntimeWarning: invalid value encountered in less
  cdf[:, :, :, i] = np.mean(ens < threshold, axis=3) * (upper_cdf -
lower_cdf) + lower_cdf / 2

I don know what is the problem

thanks in advance

greetings
