### ISSUE TITLE
Not able to run verif

### ISSUE THREAD

**Issue by dhanraj125** [WFRT/verif#110]
Executable of verif is created when I try to run, it gives the error as "pkg_resources.DistributionNotFound: The 'cftime' distribution was not found and is required by netCDF4"

cftime is installed.
Please take a look at error

Thank you.

**Comment by tnipen** [comment]
Hi I haven't seen this issue before, what version of python are you using, and what versions of cftime and netCDF4 do you have installed?

**Comment by dhanraj125** [comment]
Hello,
Sorry for the late reply.
python - 3.8.5
netCDF4 - 1.5.6
cftime - 1.4.1

Thank you.

**Comment by tnipen** [comment]
Closing this, since I am not able to reproduce the error. Sorry about this, hope it worked for you in the end.
