### ISSUE TITLE
Question regarding location (station identifier)

### ISSUE THREAD

**Issue by mokrzesa** [WFRT/verif#123]
Is it possible to feed verif nc file with a custom location (station identifier), different than the WMO ? I'm new to verif - it seems perfect for my use-case but the only problem is that stations that I have observations from do not have WMO identifier (at least not all of them)

With best regards and thanks for your help!

**Comment by tnipen** [comment]
Yes, you can use whatever number you want for the station identifier (doesn't have to be a formal WMO number), they just have to be unique.

**Comment by mokrzesa** [comment]
Thank you very much @tnipen ! I'll try it with your suggestion then 👍
