### ISSUE TITLE
Having challenge installing in Python 3.6.5 

### ISSUE THREAD

**Issue by martadd** [WFRT/verif#99]
verif seems not to be working in Python 3.6.5, Kindly help me with the installation

**Comment by tnipen** [comment]
Unfortunately, the verif code doesn't run in python 3. Do you have the possibility to install it using python 2.7?

**Comment by martadd** [comment]
Dear Thomas,
Thanks for your response. I figured it out yesterday that it doesn't work
with python 3 so i have successfully installed in python 2.7. Is it
possible to share more examples on using verif a module in python and
plotting the outputs.
Kind regads.

--
Martin Addi
Meteorologist,
Ghana Meteorological Agency
Tel: +233247489296

**Comment by tnipen** [comment]
A new python3 package has now been uploaded to pip.
